// automatically generated by the FlatBuffers compiler, do not modify

package com.peyo.rtlmex

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class DatabaseEmbeddings : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : DatabaseEmbeddings {
        __init(_i, _bb)
        return this
    }
    fun embeddings(j: Int) : com.peyo.rtlmex.Embedding? = embeddings(com.peyo.rtlmex.Embedding(), j)
    fun embeddings(obj: com.peyo.rtlmex.Embedding, j: Int) : com.peyo.rtlmex.Embedding? {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val embeddingsLength : Int
        get() {
            val o = __offset(4); return if (o != 0) __vector_len(o) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_24_3_25()
        fun getRootAsDatabaseEmbeddings(_bb: ByteBuffer): DatabaseEmbeddings = getRootAsDatabaseEmbeddings(_bb, DatabaseEmbeddings())
        fun getRootAsDatabaseEmbeddings(_bb: ByteBuffer, obj: DatabaseEmbeddings): DatabaseEmbeddings {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createDatabaseEmbeddings(builder: FlatBufferBuilder, embeddingsOffset: Int) : Int {
            builder.startTable(1)
            addEmbeddings(builder, embeddingsOffset)
            return endDatabaseEmbeddings(builder)
        }
        fun startDatabaseEmbeddings(builder: FlatBufferBuilder) = builder.startTable(1)
        fun addEmbeddings(builder: FlatBufferBuilder, embeddings: Int) = builder.addOffset(0, embeddings, 0)
        fun createEmbeddingsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startEmbeddingsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun endDatabaseEmbeddings(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
        fun finishDatabaseEmbeddingsBuffer(builder: FlatBufferBuilder, offset: Int) = builder.finish(offset)
        fun finishSizePrefixedDatabaseEmbeddingsBuffer(builder: FlatBufferBuilder, offset: Int) = builder.finishSizePrefixed(offset)
    }
}
