// automatically generated by the FlatBuffers compiler, do not modify

package com.peyo.rtlmex

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class Embedding : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : Embedding {
        __init(_i, _bb)
        return this
    }
    fun values(j: Int) : Float {
        val o = __offset(4)
        return if (o != 0) {
            bb.getFloat(__vector(o) + j * 4)
        } else {
            0.0f
        }
    }
    val valuesLength : Int
        get() {
            val o = __offset(4); return if (o != 0) __vector_len(o) else 0
        }
    val valuesAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 4)
    fun valuesInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 4)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_24_3_25()
        fun getRootAsEmbedding(_bb: ByteBuffer): Embedding = getRootAsEmbedding(_bb, Embedding())
        fun getRootAsEmbedding(_bb: ByteBuffer, obj: Embedding): Embedding {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createEmbedding(builder: FlatBufferBuilder, valuesOffset: Int) : Int {
            builder.startTable(1)
            addValues(builder, valuesOffset)
            return endEmbedding(builder)
        }
        fun startEmbedding(builder: FlatBufferBuilder) = builder.startTable(1)
        fun addValues(builder: FlatBufferBuilder, values: Int) = builder.addOffset(0, values, 0)
        fun createValuesVector(builder: FlatBufferBuilder, data: FloatArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addFloat(data[i])
            }
            return builder.endVector()
        }
        fun startValuesVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun endEmbedding(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
